config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # map '/' to be a redirect to '/discover#show'
  root 'homepage#show'

  get 'homepage/', to: 'homepage#show', as: 'homepage'
  get 'discovery/show', to: 'discovery#show', as: 'discovery_show'
  post 'discovery/next', to: 'discovery#next', as: 'discovery_next'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/models/songs.rb
class Song < ActiveRecord::Base
  attr_accessible :title, :artist, :image, :mp3
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/discovery_controller.rb
class DiscoveryController < ApplicationController

  def show
    if session[:index].nil?
      session[:index] = 1
    end
    @song = Song.find(session[:index])
    @img = '../assets/' + @song.image + '.jpg'
    @mp3 = '../assets/' + @song.mp3 + '.mp3'
  end

  def next
    session[:index] = (session[:index])%(Song.count)+ 1
    @song = Song.find(session[:index])
    @img = '../assets/' + @song.image + '.jpg'
    @mp3 = '../assets/' + @song.mp3 + '.mp3'
    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show' }
    end
  end

  def toggle

  end

  def index
  end

  def new
    # default: render 'new' template
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def show
  end

  def index
  end

  def new
    # default: render 'new' template
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def show
  end

  def index
  end

  def new
    # default: render 'new' template
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/discovery/_show.html.erb
<div class="animated slideInRight discovery_main">
  <div class="music-display">
    <div class="image-wrapper">
      <img id="song_art" src=<%= @img %> >
      <progress class="progressbar" id="progressbar" value="0" max="100"> </progress>
    </div>
  </div>

  <div class="controls">
    <h1 id="song_title"><%= @song.title %></h1>
    <h3 id="song_artist"><%= @song.artist %></h3>
  </div>
</div>
<audio id="songMP3" ontimeupdate="updateProgress()" src="<%= @mp3 %>"></audio>

app/views/discovery/show.html.erb
<html>
<%= stylesheet_link_tag 'discovery' %>
<div class="container">
  <div class="jumbotron">
    <div class="header-button home-button">
      <i onclick="<%=homepage_path%>" class="fa fa-3x fa-home" aria-hidden="true"></i>
    </div>
    <div class="header-button user">
      <i class="fa fa-3x fa-user" aria-hidden="true"></i>
    </div>
    <div class="text-center">
      <h1 class="animated bounce">Discover</h1>
      <h3>New Music. Unheard Talent.</h3>
    </div>
  </div>
  <div class="center" id="song_info">
    <div class="animated slideInRight discovery_main">
      <div class="music-display">
        <div class="image-wrapper">
          <img id="song_art" src=<%= @img %> >
          <progress class="progressbar" id="progressbar" value="0" max="100"> </progress>
        </div>
      </div>

      <div class="controls">
        <h1 id="song_title"><%= @song.title %></h1>
        <h3 id="song_artist"><%= @song.artist %></h3>
      </div>
      <audio id="songMP3" ontimeupdate="updateProgress()" src="<%= @mp3 %>"></audio>
    </div>
  </div>
  <footer class="container-fluid soundOffFooter">
    <div class="text-center">
      <p>All Rights Reserved - Copyright SoundOff Inc. &copy; 2017 </p>
    </div>
  </footer>
</div>
</html>
<script>
  var playing = true;


  $(document).ready(function(){
      window.addEventListener('keydown', myEventHandler, false);
  });


  function myEventHandler(e){
    var keyCode = e.keyCode;
    if(keyCode == 39) {
      $.ajax({
          url: "/discovery/next",
          type: 'POST',
          dataType: 'script'
      });
    }
    else if (keyCode == 38) {

    }
    else if (keyCode == 32){
        if (playing) {
            document.getElementById('songMP3').play();
        } else {
            document.getElementById('songMP3').pause();
        }
        playing = !playing
    }
  }
  function updateProgress() {
      var value = 0;
      var audio = document.getElementById('songMP3');
      if (audio.currentTime > 0) {
          value = Math.floor((100 / audio.duration) * audio.currentTime);
      }
      document.getElementById("progressbar").value = value
  }

</script>

app/views/discovery/show.js.erb
$('#song_info').html('<%= j render :partial => 'show' %>');

app/views/homepage/show.html.erb
<html>
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
  <div class="container">
    <header>
      <div class="header-content">
        <div class="header-content-inner">
          <h1 id="homeHeading" class="detail">Sound<span class="name">Off</span></h1>
          <hr>
          <h3>Revolutionizing the discovery of music.</h3>
          <a href="#about" class="btn btn-primary btn-xl page-scroll">Login</a>
          <a href="#about" class="btn btn-primary btn-xl page-scroll">Join</a>
        </div>
      </div>
    </header>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundOffDemo</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">

    <script src="https://use.fontawesome.com/9d5af17908.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'SoundOffTheme' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>